### ISSUE TITLE
Nesting Spaces

### ISSUE THREAD

**Issue by imbev** [commetchat/commet#140]
Currently, all spaces are displayed at all times. It would be preferable to have nested spaces, i.e. clicking a space could reveal sub-spaces.

**Comment by kimabjorkede** [comment]
I believe it would be better to show nested spaces in the way Discord shows  "channel groups".
Commet:
![image](https://github.com/commetchat/commet/assets/10121762/b5b89570-9dd9-4c07-b7b7-a118e44ef2cc)
Discord:
![image](https://github.com/commetchat/commet/assets/10121762/81eb7970-e107-4caf-ab94-20f57b91497a)

**Comment by Airyzz** [comment]
I agree, will probably head in this direction

**Comment by kimabjorkede** [comment]
I wonder how this would work with Mautrix Discord.
![image](https://github.com/commetchat/commet/assets/10121762/72655d47-14b1-4898-b495-31528fbc28bb)
In this case I would prefer the Discord servers be different spaces, while the channel groups and channels be rooms.
![image](https://github.com/commetchat/commet/assets/10121762/164e8d3d-d12c-4cff-a2e8-88a4c30a4258)
The way Element does it is not too nice either.

**Comment by imbev** [comment]
There is also the way that Cinny does it, which scales well.

**Comment by Airyzz** [comment]
I dont particularly love needing to "pin" spaces, but it would definitely be a solution to this bridge issue for sure

If the bridge provides any data to indicate which spaces are discord servers I would like to be able to use that to filter which should go in side bar and which should be subspaces

**Comment by RoootTheFox** [comment]
hai, i found out about Commet a few days ago and wanted to share my thanks for making a neat looking client ^^

either way, back to the issue: as of right now, I am bridging discord servers to matrix using mautrix-discord - however, im unable to easily access channels in sub-spaces/categories, as the spaces they're in are shown as "available rooms" with an option to join them, which doesn't work (the spaces are already joined)
not sure if i should open a new issue for this or if that's related:
https://foxgirl.wtf/8e35bb98ac204dbeb8f9e79b87da8955
(external link because github wouldn't let me upload the video)

**Comment by Airyzz** [comment]
thanks for the video, i didn't realise it was completely broken like this! I will try to look in to this soon
